### ISSUE TITLE
Service Provider Config clarifications

### ISSUE THREAD

**Issue by conro1108** [ietf-scim-wg/draft-sehgal-scim-delta-query#11]
In the Service Provider Configuration section, we describe 3 attributes `deltaQuery`, `supported`, and `deltaTokenExpiry` to be included in the JSON document returned by the /ServiceProviderConfig endpoint.

Looking at the related example response, it has `supported` as an attribute of complex attr `deltaQuery` - it would be good to clarify if service providers should include these 3 attributes in the ServiceProviderConfig, or if they need to include a single `deltaQuery` attribute which has fields `supported` and `deltaTokenExpiry`

**Comment by ansg-aws** [comment]
Agreed, will cla

**Comment by ansg-aws** [comment]
Agreed, will definitely clarify in next version of the document
