### ISSUE TITLE
Filtering section stray paragraph

### ISSUE THREAD

**Issue by conro1108** [ietf-scim-wg/draft-sehgal-scim-delta-query#12]
In the filtering section, the paragraph 

```
When the client makes a subsequent deltaQuery request, it should query the same Service Provider endpoint with all query parameters and values being identical to the initial query issued in the previous delta scan or full scan with the exception of the deltatoken value which should be set to a nextDeltaToken value that was returned by Service Provider in a previous delta query response.
```

seems out of place to me. Would this make more sense in one of the earlier sections describing delta query usage in divergence detection? The advice seems quite generic and not specific to filtering

**Comment by ansg-aws** [comment]
This is actually specific to filtering. This point indicates that the filtering parameters applied to the delta query should not change within subsequent delta queries. But will add additional detail to clarify more.

**Comment by ansg-aws** [comment]
This is actually specific to filtering. This point indicates that the filtering parameters applied to the delta query should not change within subsequent delta queries. But will add additional detail to clarify more in next version of the document.
