### ISSUE TITLE
Add additional context to the text

### ISSUE THREAD

**Issue by dhs-aws** [ietf-scim-wg/draft-sehgal-scim-delta-query#3]
The first paragraph in the introduction introduces the idea that the mechanism can be used for change detection.  We should note that this proposed mechanism is optional and other mechanisms may exist in future updates to the SCIM spec (e.g. event based mechanisms using SETs) and non-SCIM based mechanisms.  This change is in recognition of the fact that not all deployments will use this specific mechanism if standardized.

**Comment by ccrvincent** [comment]
A list of benefits vs. "(meta.lastModified GT $newestTimestampInLastQuery)" would be useful, too.  The mechanism already exists for this functionality, this just seems to be a helper.

**Comment by ansg-aws** [comment]
Agreed, great callout. Will include in the next version of the draft.
