### ISSUE TITLE
isDeleted is necessary, but should it be defined here?

### ISSUE THREAD

**Issue by dhs-aws** [ietf-scim-wg/draft-sehgal-scim-delta-query#8]
Should this spec introduce the concept of deletions?  I suggest keeping the specification as narrowly scoped as possible by removing this from the draft and introducing the concepts of deletion in a separate draft document.

**Comment by ansg-aws** [comment]
This isDeleted is different than soft/hard delete. isDeleted is used to get minimal information (e.g. IDs) about previously existed record forever while deleting the rest of the data and is only required for the purpose of Delta Queries. Soft Delete marks the item as deleted but actually doesn’t delete the data immediately, leaving time for the client to restore it. Time until soft deletes fully cleanup the data is frequently configured to be ~2 weeks, but maybe there is value to override it. So it make sense to keep isDeleted as part of this spec.
